### ISSUE TITLE
Wrong datatype in function header

### ISSUE THREAD

**Issue by nathancheek** [hytech-racing/code-2019#36]
https://github.com/hytech-racing/code-2019/blob/14d300f5eda48b3aa6ee75997c2c66b26a2bfefd/Vehicle/BMS_Control_Unit/BMS_Control_Unit.ino#L1129

This function header specifies a `double` output but we return an `int16_t` output. Is this correct?

**Comment by lpozdneev** [comment]
I would say that the mistake is in the header because in the line #860 `int current = get_current();` the values is assigned to an `int`.
